version: '3.8'

services:
  admin-ui:
    build:
      context: ./frontend/admin-ui
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    networks:
      - frontend-network

  evaluator-ui:
    build:
      context: ./frontend/evaluator-ui
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    networks:
      - frontend-network

  submitter-ui:
    build:
      context: ./frontend/submitter-ui
      dockerfile: Dockerfile
    ports:
      - "3002:80"
    networks:
      - frontend-network

  innovation-portal-ui:
    build:
      context: ./frontend/innovation-portal-web
      dockerfile: Dockerfile
    ports:
      - "3003:80"
    networks:
      - frontend-network

  reviewer-ui:
    build:
      context: ./frontend/reviewer-ui
      dockerfile: Dockerfile
    ports:
      - "8086:80"
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
