/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-fixed': '#001c37',
        'status-submitted-text': '#1E40AF',
        background: '#f8f9ff',
        'on-tertiary': '#ffffff',
        error: '#ba1a1a',
        'status-action-bg': '#FFF7ED',
        'saffron-accent': '#E05A10',
        'status-approved-bg': '#ECFDF5',
        'on-secondary': '#ffffff',
        'surface-container': '#e5eeff',
        'tertiary-container': '#002a1b',
        'on-tertiary-fixed-variant': '#005137',
        'on-primary-fixed-variant': '#314865',
        'text-muted': '#64748B',
        'surface-container-low': '#eff4ff',
        'status-submitted-bg': '#EFF6FF',
        'on-secondary-container': '#1d3989',
        outline: '#74777e',
        'secondary-container': '#8fa7fe',
        'secondary-fixed-dim': '#b6c4ff',
        'status-approved-border': '#A7F3D0',
        'text-secondary': '#475569',
        'gov-emerald': '#059669',
        'primary-container': '#0a2540',
        'on-surface-variant': '#43474d',
        'status-review-text': '#5B21B6',
        'tertiary-fixed-dim': '#68dba9',
        'on-primary-container': '#768dad',
        'surface-bright': '#f8f9ff',
        'primary-fixed': '#d2e4ff',
        'surface-variant': '#d3e4fe',
        'status-action-text': '#9A3412',
        'surface-crisp': '#FFFFFF',
        surface: '#f8f9ff',
        'on-secondary-fixed-variant': '#264191',
        'surface-container-high': '#dce9ff',
        'surface-subtle': '#F8FAFC',
        'surface-muted': '#F1F5F9',
        'institutional-navy': '#1E3A8A',
        primary: '#000f22',
        tertiary: '#001209',
        secondary: '#4059aa',
        'secondary-fixed': '#dce1ff',
        'on-surface': '#0b1c30',
        'on-error': '#ffffff',
        'on-primary': '#ffffff',
        'on-tertiary-fixed': '#002114',
        'on-tertiary-container': '#1a9e70',
        'on-secondary-fixed': '#00164e',
        'status-review-border': '#DDD6FE',
        'inverse-primary': '#b0c8eb',
        'error-container': '#ffdad6',
        'surface-tint': '#49607e',
        'surface-container-highest': '#d3e4fe',
        'border-hairline': '#E2E8F0',
        'ashoka-blue': '#0A2540',
        'inverse-surface': '#213145',
        'surface-container-lowest': '#ffffff',
        'status-action-border': '#FED7AA',
        'border-strong': '#CBD5E1',
        'surface-dim': '#cbdbf5',
        'text-primary': '#0F172A',
        'on-background': '#0b1c30',
        'status-submitted-border': '#BFDBFE',
        'primary-fixed-dim': '#b0c8eb',
        'inverse-on-surface': '#eaf1ff',
        'outline-variant': '#c4c6ce',
        'status-approved-text': '#065F46',
        'tertiary-fixed': '#85f8c4',
        'status-review-bg': '#F5F3FF',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'space-2xs': '0.125rem',
        'space-base': '1rem',
        'space-lg': '1.5rem',
        'form-max-width': '42rem',
        'space-sm': '0.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'space-xs': '0.25rem',
        'container-max-width': '72rem',
        'space-md': '0.75rem',
        'space-3xl': '4rem',
        'gutter-desktop': '1.5rem',
        'gutter-mobile': '1rem',
      },
      fontFamily: {
        'headline-xl': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'mono-code': ['JetBrains Mono', 'monospace'],
        'headline-sm': ['Inter', 'sans-serif'],
        'headline-xl-mobile': ['Inter', 'sans-serif'],
        'label-lg': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '700' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '26px', letterSpacing: '0em', fontWeight: '400' }],
        'mono-code': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-sm': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '600' }],
        'headline-xl-mobile': ['26px', { lineHeight: '34px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '400' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '22px', letterSpacing: '0em', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
